# Project information
site_name: UNIHIKER  Documentation
site_url: https://www.unihiker.com/
site_author: Unihiker Team
site_description: >-
  UNIHIKER  Documentation

# Repository
repo_name: UNIHIKERTeam/Docs
repo_url: https://github.com/UNIHIKER/unihiker-docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2024 - 2029 UNIHIKER Team'

# Configuration

theme:
  name: material
  custom_dir: overrides
  nav_style: dark
  features:
    - navigation.path  # Enable breadcrumbs

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.path
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - navigation.top
  
  
  palette:
    - scheme: default
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico

  #icon:
    #logo: material/library
  logo: assets/images/uniilogo_w.png

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
# hooks:
  # - material/.overrides/hooks/translations.py

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://www.unihiker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/UNIHIKER/unihiker-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UNIHIKER
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/UNIHIKER
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rvvfNCvBKv
#  alternate:
#    - name: Chinese
#      link: /zh/
#      lang: zh

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.snippets
  # - markdown.extensions.meta

extra_css:
  - stylesheets/extra.css

nav:
  - Home: https://www.unihiker.com/
  - Documentation: 
    - index.md 
    - 🚩 Getting Started: 
      - Getting Started: get-started.md
      - Jupyter Notebook: GettingStarted/gettingstarted_jupyternotebook.md
      - Mind+ Python & Graphical Python: GettingStarted/gettingstarted_mind+.md
      - VSCode - Python: GettingStarted/gettingstarted_vscode.md
      - Python IDLE - Python: GettingStarted/gettingstarted_python_idle.md
      - Tonny - Python: GettingStarted/gettingstarted_thonny.md
      - SSH Tools: GettingStarted/gettingstarted_ssh.md
    - 🌟 Examples:
      - Python Coding Examples:
        - Examples/PythonCodingExamples/index.md
        - Basic Examples:
          - 1.Hello,Unihiker: Examples/PythonCodingExamples/BasicExamples/examples_py_hellounihiker.md
          - 2.System Time: Examples/PythonCodingExamples/BasicExamples/examples_py_system_time.md
          - 3.Starry Sky: Examples/PythonCodingExamples/BasicExamples/examples_py_starry_sky.md
          - 4.Emoticon Master: Examples/PythonCodingExamples/BasicExamples/examples_py_emoticon_master.md
          - 5.Interactive Button Screen: Examples/PythonCodingExamples/BasicExamples/examples_py_interactive_button_screen.md
          - 6.Draw a Clock: Examples/PythonCodingExamples/BasicExamples/examples_py_draw_your_own_clock.md
          - 7.QR Code Display: Examples/PythonCodingExamples/BasicExamples/examples_py_qr_code_display.md
          - 8.Draw a Hexagon: Examples/PythonCodingExamples/BasicExamples/examples_py_draw_a_hexagon.md
          - 9.Color Picker: Examples/PythonCodingExamples/BasicExamples/examples_py_color_picker.md
          - 10.Draw the Olympic Rings: Examples/PythonCodingExamples/BasicExamples/examples_py_draw_the_olympic_rings.md
          - 11.Where is the Mouse: Examples/PythonCodingExamples/BasicExamples/examples_py_where_is_the_mouse.md
          - 12.Switch Albums with Keyboard: Examples/PythonCodingExamples/BasicExamples/examples_py_switch_albums_with_keyboard.md
          - 13.Recoder: Examples/PythonCodingExamples/BasicExamples/examples_py_recoder.md
          - 14.Music Player: Examples/PythonCodingExamples/BasicExamples/examples_py_music_player.md
          - 15.LED Flashing: Examples/PythonCodingExamples/BasicExamples/examples_py_led_flashing.md
          - 16.Button Light: Examples/PythonCodingExamples/BasicExamples/examples_py_button_lights.md
          - 17.Luminosity Detector: Examples/PythonCodingExamples/BasicExamples/examples_py_luminosity_detector.md
          - 18.Digital Piano: Examples/PythonCodingExamples/BasicExamples/examples_py_digital_piano.md
          - 19.Noise Monitor: Examples/PythonCodingExamples/BasicExamples/examples_py_noise_monitor.md
          - 20.Pedometer: Examples/PythonCodingExamples/BasicExamples/examples_py_pedometer.md
        - Intermediate Examples:
          - 1.Blinking LED: Examples/PythonCodingExamples/IntermediateExamples/1_Blinking_LED.md
          - 2.Colourful Light Strip: Examples/PythonCodingExamples/IntermediateExamples/2_Colourful_Light_Strip.md
          - 3.Smart Home Temperature and Humidity Monitor: Examples/PythonCodingExamples/IntermediateExamples/3_Smart_home_temperature_and_humidity_Monitor.md
          - 4.RGB LED Color Palette: Examples/PythonCodingExamples/IntermediateExamples/4_RGB_LED_Color_Palette.md
          - 5.Plant Moisture Monitoring: Examples/PythonCodingExamples/IntermediateExamples/5_Plant_Moisture_Monitoring.md
          - 6.Ultrasonic Distance Meter: Examples/PythonCodingExamples/IntermediateExamples/6_Ultrasonic_Range_Finder.md
          - 7.Servo Motor Control: Examples/PythonCodingExamples/IntermediateExamples/7_Servo_Motor_Control.md
          - 8.Bluetooth(with UNIHIKER): Examples/PythonCodingExamples/IntermediateExamples/8_Bluetooth_Unihiker2Unihiker.md
          - 9.Bluetooth(with BLELink): Examples/PythonCodingExamples/IntermediateExamples/9_Bluetooth_Unihiker2BLELink.md
          - 10.Bluetooth(with APP): Examples/PythonCodingExamples/IntermediateExamples/10_Bluetooth_Unihiker2BLEAPP.md
        - Advance Examples:
            - 1.AI Voice Light: Examples/PythonCodingExamples/AdvanceExamples/1_AI_Voice_Controlled_Lights.md
            - 2.Speech Synthesis Assistant: Examples/PythonCodingExamples/AdvanceExamples/2_Speech_Synthesis_Assistant.md
            - 3.DIY Camera: Examples/PythonCodingExamples/AdvanceExamples/3_DIY_Camera.md
            - 4.Smart Home Monitoring: Examples/PythonCodingExamples/AdvanceExamples/4_Smart_Home_Monitoring.md
            #- 5.License Plate Recognition: Examples/PythonCodingExamples/AdvanceExamples/5_License_Plate_Recognition.md
            - 6.Color-Following Car: Examples/PythonCodingExamples/AdvanceExamples/6_Color_Following_Car.md
            #- 7.Text Recognition: Examples/PythonCodingExamples/AdvanceExamples/7_Text_Recognition.md
            #- 8.QR Code Scanner: Examples/PythonCodingExamples/AdvanceExamples/8_QR_Code_Scanner.md
            #- 9.Face Recognition: Examples/PythonCodingExamples/AdvanceExamples/9_Face_Recognition.md
            - 10.IoT Smart Home: Examples/PythonCodingExamples/AdvanceExamples/10_IoT_Smart_Home.md
    - 📜 Language Reference:
      - Part1 UNIHIKER Library:
        - LanguageReference/UNIHIKER_Library/index.md
        - Unihiker Library - Introduction: LanguageReference/UNIHIKER_Library/unihiker_library_introduction.md
        - General Knowledge and Features: LanguageReference/UNIHIKER_Library/GeneralKnowledgeAndFeatures/index.md
        - Screen Display:
          - 1.draw_text(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_text.md
          - 2.draw_digit(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_digit.md
          - 3.draw_image(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_image.md
          - 4.draw_emoji(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_emoji.md
          - 5.draw_clock(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_clock.md
          - 6.fill_clock(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_fill_clock.md
          - 7.draw_qr_code(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_draw_qr_code.md
          - 8.add_button(): LanguageReference/UNIHIKER_Library/ScreenDisplay/reference_unihiker_add_button.md
        - Screen Rendering Graphics:
          - 1.draw_line(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_draw_line.md
          - 2.draw_rect(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_draw_rect.md
          - 3.fill_rect(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_fill_rect.md
          - 4.draw_round_rect(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_draw_round_rect.md
          - 5.fill_round_rect(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_fill_round_rect.md
          - 6.draw_circle(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_draw_circle.md
          - 7.fill_circle(): LanguageReference/UNIHIKER_Library/ScreenRenderingGraphics/reference_unihiker_fill_circle.md
        - Mouse And Keyboard:
          - 1.on_mouse_move(): LanguageReference/UNIHIKER_Library/MouseAndKeyboard/reference_unihiker_on_mouse_move.md
          - 2.on_key_click(): LanguageReference/UNIHIKER_Library/MouseAndKeyboard/reference_unihiker_on_key_click.md
        - Multi Threading:
          - 1.start_thread(): LanguageReference/UNIHIKER_Library/MultiThreading/reference_unihiker_start_thread.md
          - 2.stop_thread(): LanguageReference/UNIHIKER_Library/MultiThreading/reference_unihiker_stop_thread.md
        - Audio Class:
          - 1.Recording Audio(record): LanguageReference/UNIHIKER_Library/AudioClass/reference_unihiker_recording_audio_record.md
          - 2.Audio Playback(play): LanguageReference/UNIHIKER_Library/AudioClass/reference_unihiker_audio_playback_play.md
      - Part2 PinPong Library:
        - LanguageReference/PinPong_Library/index.md
        - Pinpong Library - Introduction: LanguageReference/PinPong_Library/pinpong_library_introduction.md
        - Function Onboard:
          - 1.L LED: LanguageReference/PinPong_Library/FunctionOnboard/1_L_LED_.md
          - 2.Button A and Button B: LanguageReference/PinPong_Library/FunctionOnboard/2_Button_A_and_Button_B.md
          - 3.Light Sensor: LanguageReference/PinPong_Library/FunctionOnboard/3_Light_Sensor.md
          - 4.Accelerometer and Gyroscope: LanguageReference/PinPong_Library/FunctionOnboard/4_Accelerometer_and_Gyroscope.md
          - 5.Buzzer: LanguageReference/PinPong_Library/FunctionOnboard/5_Buzzer.md
        - Digital IO & Analog IO:
          - 1.Digital Output(GPIO): LanguageReference/PinPong_Library/DigitalIOAndAnlogIO/1_Digital_Output_GPIO_.md
          - 2.Digital Input(GPIO): LanguageReference/PinPong_Library/DigitalIOAndAnlogIO/2_Digital_Input_GPIO_.md
          - 3.Analog Input(ADC): LanguageReference/PinPong_Library/DigitalIOAndAnlogIO/3_Analog_Input_ADC_.md
          - 4.Analog Output(PWM): LanguageReference/PinPong_Library/DigitalIOAndAnlogIO/4_Analog_Output_PWM_.md
        - Communication:
          - 1.Serial Port(UART): LanguageReference/PinPong_Library/Communication/1_Serial_Port_UART_.md
          - 2.I2C(Inter Integrated Circuit): LanguageReference/PinPong_Library/Communication/2_I2C_Inter_Integrated_Circuit_.md
          - 3.SPI(Serial Peripheral Interface): LanguageReference/PinPong_Library/Communication/3_SPI_Serial_Peripheral_Interface_.md
        - Popular Modules:
          - 1.Servo: LanguageReference/PinPong_Library/PopularModules/3_Servo.md
          - 2.LED Strip: LanguageReference/PinPong_Library/PopularModules/4_LED_Strip.md
          - 3.DHT11 Temperature & Humidity Sensor: LanguageReference/PinPong_Library/PopularModules/1_DHT11_Temperature_Humidity_Sensor.md
          - 4.Ultrasonic Sensor: LanguageReference/PinPong_Library/PopularModules/2_Ultrasonic_sensor.md
          - 5.OLED 2864 Display Screen: LanguageReference/PinPong_Library/PopularModules/5_OLED_2864_Display_Screen.md
          - 6.Color Recognition: LanguageReference/PinPong_Library/PopularModules/6_Color_recognition.md
      - Part3 USB Devices:
        - USB Camera: LanguageReference/USBDevices/USB_Carema.md
        - USB Speaker: LanguageReference/USBDevices/USB_Speaker.md
    - 🪄 Playground:
      - STEM: Playground/STEM.md
      - AI: Playground/AI.md
      - IOT: Playground/IOT.md
      - Tutorial Series(Block): Playground/BlockTutorialSeries.md
      - Tutorial Series(Code): Playground/CodeTutorialSeries.md
    - 🚀 Hardware Reference:
      - 1.Introduction: HardwareReference/hardware_reference_introduction.md
      - 2.On-board Components: HardwareReference/hardware_reference_onboard_components.md
      - 3.UNIHIKER System Framework: HardwareReference/hardware_reference_unihiker_system_framework.md
      - 4.Specification: HardwareReference/hardware_reference_specification.md
      - 5.Board Overview: HardwareReference/hardware_reference_board_overview.md
      - 6.Dimension: HardwareReference/hardware_reference_dimension.md
      - 7.SVG & 3D File: HardwareReference/hardware_reference_svg_3d_file.md
    - 🧩 System and Configuration:
      - 1.Multi Connection Methods: SystemAndConfiguration/system_and_configuration_multi_connection_methods.md
      - 2.Home Menu: SystemAndConfiguration/system_and_configuration_home_menu.md
      - 3.Local Web Page: SystemAndConfiguration/system_and_configuration_local_web_page.md
      - 4.SSH Connection: SystemAndConfiguration/system_and_configuration_ssh_connection.md
      - 5.SMB File Sharing: SystemAndConfiguration/system_and_configuration_smb_file_sharing.md
      - 6.Remote Desktop: SystemAndConfiguration/system_and_configuration_remote_desktop.md
      - 7.OS: 
        - OS: SystemAndConfiguration/unihiker_os.md
        - OS Image Guide: SystemAndConfiguration/unihiker_os_image.md
        - Burning Guide: SystemAndConfiguration/unihiker_os_burn.md
    - 🔧 Troubleshooting: 
      - Troubleshooting/index.md
      - Error firmware version self boardname KeyError: Troubleshooting/Error_firmware_version_self_boardname__KeyError_.md
      - Error NoneType object has no attribute boardname : Troubleshooting/Error_NoneType_object_has_no_attribute_boardname_.md
      - Error python3 can't open file : Troubleshooting/Error_python3__can_t_open_file_.md
      - Error RuntimeError Analog map retrieval time out or the readings from onboard components all 0 : Troubleshooting/Error_RuntimeError_Analog_map_retrieval_time_out_or_the_readings_from_onboard_components_all_0.md
      - How can I adjust the screen brightness of UNIHIKER : Troubleshooting/How_can_I_adjust_the_screen_brightness_of_UNIHIKER.md
      - How can I get the Mind graphical program to run on the UNIHIKER after disconnecting it from my computer : Troubleshooting/How_can_I_get_the_Mind_graphical_program_to_run_on_the_UNIHIKER_after_disconnecting_it_from_my_computer.md
      - How can I upload resource files such as images required for my program to UNIHIKER : Troubleshooting/How_can_I_upload_resource_files_such_as_images_required_for_my_program_to_UNIHIKER.md
      - How can multiple Unihikers be plugged into the main computer and assigned to different addresses : Troubleshooting/How_can_multiple_Unihikers_be_plugged_into_the_main_computer_and_assigned_to_different_addresses.md
      - How to choose an expansion board for UNIHIKER : Troubleshooting/How_to_choose_an_expansion_board_for_UNIHIKER.md
      - How to connect WiFi: Troubleshooting/How_to_connect_wifi.md
      - How to connect a Bluetooth speaker : Troubleshooting/How_to_connect_a_Bluetooth_speaker.md
      - How to set time, date and timezone on UNIHIKER : Troubleshooting/How_to_set_time_date_and_timezone_on_UNIHIKER.md
      - How to shut down : Troubleshooting/How_to_shut_down.md
      - How to update the system time if the SIoT time is incorrect : Troubleshooting/How_to_update_the_system_time_if_the_SIOT_time_is_incorrect.md
      - Installing Python library failed Warning Retrying Errno 3 : Troubleshooting/Installing_Python_library_failed_Warning__Retrying_Errno_3.md
      - The UNIHIKER cannot be connected to Mindplus : Troubleshooting/The_UNIHIKER_cannot_be_connected_to_Mind.md
      - What should I do if the screen is black, white and I can't enter the system : Troubleshooting/What_should_I_do_if_the_screen_is_black_white_and_I_can_t_enter_the_system.md

  - Forum: https://www.dfrobot.com/forum/?t=947&p=1
  - Contact Us: 
    - 1.Technical Discussion: ContactUs/contactus_technical_discussion.md
    - 2.Contact Us: ContactUs/contactus_contact_us.md

