# Project information
site_name: UNIHIKER  Documentation
site_url: https://www.unihiker.com/
site_author: Unihiker Team
site_description: >-
  UNIHIKER  Documentation

# Repository
repo_name: UNIHIKERTeam/Docs
repo_url: https://github.com/UNIHIKER/unihiker-docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2024 - 2029 UNIHIKER Team'

# Configuration

theme:
  name: material
  nav_style: dark
  features:
    - navigation.path  # Enable breadcrumbs

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.path
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - navigation.top
  
  
  palette:
    - scheme: default
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico

  #icon:
    #logo: material/library
  logo: assets/images/uniilogo.png

# Plugins
plugins:
  - search:
      separator: '[/s/-,:!=/[/]()"`/]+|/.(?!/d)|&[lg]t;|(?!/b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
# hooks:
  # - material/.overrides/hooks/translations.py

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://www.unihiker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/UNIHIKER
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UNIHIKER
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/UNIHIKER
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rvvfNCvBKv
#  alternate:
#    - name: Chinese
#      link: /zh/
#      lang: zh

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  # - markdown.extensions.meta

extra_css:
  - stylesheets/extra.css

nav:
  - HOME: https://www.unihiker.com/
  - WIKI: 
    - index.md 
    - 🚩 Getting Started: 
      - Getting Started: wiki//GettingStarted/get-started.md
      - Jupyter Notebook: wiki/GettingStarted/gettingstarted_jupyternotebook.md
      - Mind+ Python & Graphical Python: wiki/GettingStarted/gettingstarted_mind+.md
      - VSCode - Python: wiki/GettingStarted/gettingstarted_vscode.md
      - Python IDLE - Python: wiki/GettingStarted/gettingstarted_python_idle.md
      - Tonny - Python: wiki/GettingStarted/gettingstarted_thonny.md
      - SSH Tools: wiki/GettingStarted/gettingstarted_ssh.md
    - 🌟 Examples:
      - Python Coding Examples:
        - Basic Examples:
          - 1.Hello,Unihiker: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_hellounihiker.md
          - 2.System Time: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_system_time.md
          - 3.Starry Sky: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_starry_sky.md
          - 4.Emoticon Master: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_emoticon_master.md
          - 5.Interactive Button Screen: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_interactive_button_screen.md
          - 6.Draw your Own Clock: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_draw_your_own_clock.md
          - 7.QR code display: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_qr_code_display.md
          - 8.Draw a hexagon: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_draw_a_hexagon.md
          - 9.Color Picker: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_color_picker.md
          - 10.Draw the Olympic Rings: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_draw_the_olympic_rings.md
          - 11.Where is the Mouse: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_where_is_the_mouse.md
          - 12.Switch albums with keyboard: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_switch_albums_with_keyboard.md
          - 13.Recoder: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_recoder.md
          - 14.Music Player: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_music_player.md
          - 15.LED Flashing: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_led_flashing.md
          - 16.Button lights: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_button_lights.md
          - 17.Luminosity detector: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_luminosity_detector.md
          - 18.Digital Piano: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_digital_piano.md
          - 19.Noise Monitor: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_noise_monitor.md
          - 20.Pedometer: wiki/Examples/PythonCodingExamples/BasicExamples/examples_py_pedometer.md
    - 📜 Language Reference:
      - Part1 UNIHIKER Libs:
        - Screen Display:
          - 1.draw_text(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_text.md
          - 2.draw_digit(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_digit.md
          - 3.draw_image(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_image.md
          - 4.draw_emoji(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_emoji.md
          - 5.draw_clock(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_clock.md
          - 6.fill_clock(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_fill_clock.md
          - 7.draw_qr_code(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_draw_qr_code.md
          - 8.add_button(): wiki/LanguageReference/Part1UNIHIKER/ScreenDisplay/reference_unihiker_add_button.md
        - Screen Rendering Graphics:
          - 1.draw_line(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_draw_line.md
          - 2.draw_rect(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_draw_rect.md
          - 3.fill_rect(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_fill_rect.md
          - 4.draw_round_rect(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_draw_round_rect.md
          - 5.fill_round_rect(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_fill_round_rect.md
          - 6.draw_circle(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_draw_circle.md
          - 7.fill_circle(): wiki/LanguageReference/Part1UNIHIKER/ScreenRenderingGraphics/reference_unihiker_fill_circle.md
        - Mouse And Keyboard:
          - 1.on_mouse_move(): wiki/LanguageReference/Part1UNIHIKER/MouseAndKeyboard/reference_unihiker_on_mouse_move.md
          - 2.on_key_click(): wiki/LanguageReference/Part1UNIHIKER/MouseAndKeyboard/reference_unihiker_on_key_click.md
        - Multi Threading:
          - 1.start_thread(): wiki/LanguageReference/Part1UNIHIKER/MultiThreading/reference_unihiker_start_thread.md
          - 2.stop_thread(): wiki/LanguageReference/Part1UNIHIKER/MultiThreading/reference_unihiker_stop_thread.md
        - Audio Class:
          - 1.Recording Audio(record): wiki/LanguageReference/Part1UNIHIKER/AudioClass/reference_unihiker_recording_audio_record.md
          - 2.Audio Playback(play): wiki/LanguageReference/Part1UNIHIKER/AudioClass/reference_unihiker_audio_playback_play.md
    - 🚀 Hardware Reference:
      - 1.Introduction: wiki/HardwareReference/hardware_reference_introduction.md
      - 2.On-board Components: wiki/HardwareReference/hardware_reference_onboard_components.md
      - 3.UNIHIKER System Framework: wiki/HardwareReference/hardware_reference_unihiker_system_framework.md
      - 4.Specification: wiki/HardwareReference/hardware_reference_specification.md
      - 5.Board Overview: wiki/HardwareReference/hardware_reference_board_overview.md
      - 6.Dimension: wiki/HardwareReference/hardware_reference_dimension.md
      - 7.SVG & 3D File: wiki/HardwareReference/hardware_reference_svg_3d_file.md
    - 🧩 System and Configuration:
      - 1.Multi connection methods: wiki/SystemAndConfiguration/system_and_configuration_multi_connection_methods.md
      - 2.Home Menu: wiki/SystemAndConfiguration/system_and_configuration_home_menu.md
      - 3.Local Web Page: wiki/SystemAndConfiguration/system_and_configuration_local_web_page.md
      - 4.SSH Connection: wiki/SystemAndConfiguration/system_and_configuration_ssh_connection.md
      - 5.SMB File Sharing: wiki/SystemAndConfiguration/system_and_configuration_smb_file_sharing.md
      - 6.Remote Desktop: wiki/SystemAndConfiguration/system_and_configuration_remote_desktop.md
      - 7.Burn OS Image: wiki/SystemAndConfiguration/system_and_configuration_burn_os_image.md
    - 😀 Contact Us:
      - 1.Technical Discussion: wiki/ContactUs/contactus_technical_discussion.md
      - 2.Contact Us: wiki/ContactUs/contactus_contact_us.md



          

  - FORUM: https://www.dfrobot.com/forum/?t=947&p=1
  - CONTACT US: https://www.unihiker.com/

