# Project information
site_name: UNIHIKER  Documentation
site_url: https://www.unihiker.com/
site_author: Unihiker Team
site_description: >-
  UNIHIKER  Documentation

# Repository
repo_name: UNIHIKERTeam/Docs
repo_url: https://github.com/UNIHIKER/unihiker-docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2024 - 2029 UNIHIKER Team'

# Configuration

theme:
  name: material
  nav_style: dark

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.path
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - navigation.top
  
  
  palette:
    - scheme: default
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico

  #icon:
    #logo: material/library
  logo: assets/images/uniilogo.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
# hooks:
  # - material/.overrides/hooks/translations.py

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://www.unihiker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/UNIHIKER
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UNIHIKER
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/UNIHIKER
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rvvfNCvBKv
#  alternate:
#    - name: Chinese
#      link: /zh/
#      lang: zh

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  # - markdown.extensions.meta

extra_css:
  - stylesheets/extra.css

nav:
  - HOME: https://www.unihiker.com/
  - WIKI: 
    - index.md 
    - 😀 Getting Started: 
      -  Getting Started: wiki/get-started.md
      - Jupyter Notebook: wiki/GettingStarted/getting_started_jupyter_notebook.md
      - Mind+ Python & Graphical Python: wiki/GettingStarted/getting_started_mindplus.md
      - VSCode - Python: wiki/GettingStarted/getting_started_vscode.md
      - Python IDLE - Python: wiki/GettingStarted/getting_started_python_idle.md
      - Tonny - Python: wiki/GettingStarted/getting_started_thonny.md

  - FORUM: https://www.dfrobot.com/forum/?t=947&p=1
  - CONTACT US: https://www.unihiker.com/

