name: git2gitee
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: liliang9693/hub-mirror-action@master
      with:
        src: 'github/UNIHIKER'
        dst: 'gitee/liliang9693'
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        static_list: 'unihiker-docs'
        timeout: '1h'
        force_update: true
        debug: true
